services:
  postgres:
    container_name: 'postgres-magalu'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=magaludb'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5432:5432'